services:
  - name: araya-portfolio
    type: web
    env: python
    build:
      commands:
        - pip install -r requirements.txt
        - python manage.py collectstatic --noinput
    run:
      command: gunicorn portfolio_backend.wsgi --bind 0.0.0.0:$PORT
    env:
      - name: DEBUG
        value: "False"
      - name: SECRET_KEY
        generateValue: true
      - name: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,legal-joceline-arusoftwaresolutions-366e2846.koyeb.app,araya-haftu.duckdns.org,www.araya-haftu.duckdns.org"
      - name: EMAIL_HOST
        value: "smtp.gmail.com"
      - name: EMAIL_PORT
        value: "587"
      - name: EMAIL_USE_TLS
        value: "True"
      - name: EMAIL_HOST_USER
        value: "arayahaftu1229@gmail.com"
      - name: EMAIL_HOST_PASSWORD
        secret: true
